sudo: false
language: node_js
node_js:
  - 4
notifications:
  on_pull_requests: false
  webhooks:
    urls:
      - https://hooks.frederic-hemberger.de/travis.php
    on_success: always
    on_failure: never
    on_start: never
