express:
  port: 3000
  baseurl: "http://localhost:3000"
  shutdownTimeout: 30000
  caching:
    favicon: 0
    public: 0
uri:
  timeout: 10000
  ressourceTimeout: 10000
upload:
  maxFilesize: 1048576                 # 1 MB
  timeout: 10000
logging:
  access:
    enabled: true
    format: dev
  application:
    enabled: true
analytics:
  enabled: false
  siteId: 0
  host:
